[project]
name = "crypto-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agents>=1.4.0",
    "dotenv>=0.9.9",
    "openai>=1.102.0",
    "openai-agents>=0.2.9",
]

[tool.uv.workspace]
members = ["context"]
